# Imagen base
FROM node:20

# Carpeta de trabajo
WORKDIR /app

# Instala dependencias
COPY package*.json ./
RUN npm install

# Copia el resto del código
COPY . .

# Exponer el puerto de Vite
EXPOSE 5173

# Comando para desarrollo
CMD ["npm", "run", "dev"]
